addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.3")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "3.9.13")
addSbtPlugin("com.github.sbt"    % "sbt-pgp"       % "2.1.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.13")