name: Check Code Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # brew install sbt; cd graphql-java-codegen-sbt-plugin; sbt fmt or sbt check
      - name: Check Scala Code Style
        working-directory: plugins/sbt/graphql-java-codegen-sbt-plugin
        run: sbt check 
        
      - name: Check Code Style
        env:
          WORKDIR: ./
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECKSTYLE_CONFIG: config/checkstyle/graphql-codegen-check-style.xml
          REVIEWDOG_VERSION: v0.11.0
        run: |
          wget -O - -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.41/checkstyle-8.41-all.jar > /opt/checkstyle.jar
          wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /opt ${REVIEWDOG_VERSION}
          java -jar /opt/checkstyle.jar "${WORKDIR}" -c "${CHECKSTYLE_CONFIG}"  -f xml \
               | /opt/reviewdog -f=checkstyle \
                    -reporter="${INPUT_REPORTER:-github-pr-check}" \
                    -filter-mode="${INPUT_FILTER_MODE:-added}" \
                    -fail-on-error="${INPUT_FAIL_ON_ERROR:-false}"
