name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      working-directory: plugins/sbt/graphql-java-codegen-sbt-plugin
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build sbt plugin
      working-directory: plugins/sbt/graphql-java-codegen-sbt-plugin
      run: sbt compile publishLocalSigned --debug

    - name: Build sbt client example
      working-directory: plugins/sbt/graphql-java-codegen-sbt-plugin/sbt-codegen-exmaple
      run: sbt compile
